# Boost Bluetooth signal to maximum
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_PHY_2M=n

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable mouse/trackpad support
CONFIG_ZMK_POINTING=y

# Enable I2C for trackpad
CONFIG_I2C=y

# Enable the ADBS-A320 trackpad driver
CONFIG_ADBS_A320=y
